services:
  mongo:
    image: mongo:latest
    container_name: cau02-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - app_net

  nodeapp:
    build: ./app
    container_name: cau02-nodeapp
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      PORT: 3000
      MONGO_URL: mongodb://mongo:27017/labdb
    ports:
      - "3000:3000"
    networks:
      - app_net

volumes:
  mongo_data:

networks:
  app_net:
    driver: bridge
